services:

  db:
    image: postgres
    restart: no
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: admin
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data

  adminer:
    image: adminer
    restart: no
    ports:
      - 8080:8080
